export CUDA_VISIBLE_DEVICES=0
python3 multimodal2text/BLIP/pretrain.py \
    --model_name_or_path Salesforce/blip-vqa-base \
    --config_name Salesforce/blip-vqa-base \
    --processor_name Salesforce/blip-vqa-base \
    --train_file data/trec-pds.pretrain.m2t.product2query.jsonl \
    --max_src_length 16 \
    --max_tgt_length 16 \
    --output_dir models/blip-vqa-base-product2title/ \
    --overwrite_output_dir true \
    --do_train --do_eval \
    --save_strategy steps \
    --max_steps 50000 \
    --save_steps 12500 \
    --eval_steps 2500 \
    --save_strategy steps \
    --evaluation_strategy steps \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --eval_accumulation_steps 2 \
    --learning_rate 2e-5 \
    --lr_scheduler_type cosine \
    --weight_decay 0.05 \
    --datacollator product2title \
    --remove_unused_columns false \
    --report_to wandb \
    --overwrite_output_dir true \
    --template_src "What is the possible title for this product? title:"\
    --template_tgt "{0}" \
    --run_name blip-vqa-base-pds-pretrain
