python3 text2text/train.py \
    --model_name_or_path t5-base \
    --config_name t5-base \
    --tokenizer_name t5-base \
    --train_file data/trec-pds.train.product2query.jsonl \
    --max_src_length 384  \
    --max_tgt_length 16 \
    --output_dir models/t5-base-product2query/ \
    --overwrite_output_dir true \
    --do_train --do_eval \
    --save_strategy steps \
    --max_steps 30000 \
    --save_steps 2500 \
    --eval_steps 2500 \
    --save_strategy steps \
    --evaluation_strategy steps \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 32 \
    --learning_rate 1e-3 \
    --lr_scheduler_type constant \
    --remove_unused_columns false \
    --report_to wandb \
    --overwrite_output_dir true \
    --template "{0} | {1} | {2}" \
    --run_name pds-t2t-1e3
